version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    image: node:14-alpine
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rrenan
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
